# Global header information:
name: "sbnd_dl_anatree"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree


software: "/n/holylfs/LABS/guenette_lab/production/yml-configs/sbnd_dl/larsoft.yml"

# Block for defining stages.  Can include multiple stages
stages:

    - cosmics:
        fcl:
          - anatree_sbnd.fcl
        n_jobs: 81
        event_target: 20000
        events_per_job: -1
        input:
            dataset: sbnd_dl_cosmics_larsoft # Can be none or a name
            n_files: 1
        output:
            location: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree/cosmics
            dataset: sbnd_dl_cosmics_anatree
            anaonly: true
        memory: 4000
        time: 06:00:00

    - NC:
        fcl:
          - anatree_sbnd.fcl
        n_jobs: 895
        event_target: 20000
        events_per_job: -1
        input:
            dataset: sbnd_dl_NC_larsoft # Can be none or a name
            n_files: 1
        output:
            location: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree/NC
            dataset: sbnd_dl_NC_anatree
            anaonly: true
        memory: 4000
        time: 06:00:00

    - NC_cosmics:
        fcl:
          - anatree_sbnd.fcl
        n_jobs: 907
        event_target: 20000
        events_per_job: -1
        input:
            dataset: sbnd_dl_NC_cosmics_larsoft # Can be none or a name
            n_files: 1
        output:
            location: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree/NC_cosmics
            dataset: sbnd_dl_NC_cosmics_anatree
            anaonly: true
        memory: 4000
        time: 06:00:00

    - nueCC:
        fcl:
          - anatree_sbnd.fcl
        n_jobs: 918
        event_target: 20000
        events_per_job: -1
        input:
            dataset: sbnd_dl_nueCC_larsoft # Can be none or a name
            n_files: 1
        output:
            location: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree/nueCC
            dataset: sbnd_dl_nueCC_anatree
            anaonly: true
        memory: 4000
        time: 06:00:00

    - nueCC_cosmics:
        fcl:
          - anatree_sbnd.fcl
        n_jobs: 917
        event_target: 20000
        events_per_job: -1
        input:
            dataset: sbnd_dl_nueCC_cosmics_larsoft # Can be none or a name
            n_files: 1
        output:
            location: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree/nueCC_cosmics
            dataset: sbnd_dl_nueCC_cosmics_anatree
            anaonly: true
        memory: 4000
        time: 06:00:00

    - numuCC:
        fcl:
          - anatree_sbnd.fcl
        n_jobs: 268
        event_target: 20000
        events_per_job: -1
        input:
            dataset: sbnd_dl_numuCC_larsoft # Can be none or a name
            n_files: 1
        output:
            location: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree/numuCC
            dataset: sbnd_dl_numuCC_anatree
            anaonly: true
        memory: 4000
        time: 06:00:00

    - numuCC_cosmics:
        fcl:
          - anatree_sbnd.fcl
        n_jobs: 888
        event_target: 20000
        events_per_job: -1
        input:
            dataset: sbnd_dl_numuCC_cosmics_larsoft # Can be none or a name
            n_files: 1
        output:
            location: /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/anatree/numuCC_cosmics
            dataset: sbnd_dl_numuCC_cosmics_anatree
            anaonly: true
        memory: 4000
        time: 06:00:00


