# Global header information:
name: "next_new_detsim"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Other/NEXUS_NEXT_v1_04_00/art/

# Block for defining the larsoft setup. Reference a file
software: "/n/holylfs02/LABS/guenette_lab/production/yml-configs/next/new_bkg_sim/artnext.yml"

# Block for defining stages.  Can include multiple stages
stages:

    - evtmxr:
        config:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/DepletedXe_detsim
        n_jobs: 700
        # max_concurrent_jobs: 180
        events_per_job: -1
        input:
            dataset: nexus_NEW_DepletedXe # Can be none or a name
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Other/NEXUS_NEXT_v1_04_00/art/
            dataset: nexus_NEW_DepletedXe_detsim
            anaonly: false
            experiment: next
            project: NEWDepletedXe
            subproject: detsim
            slice: EventMixer

        memory: 4000
        time: 48:00:00
