# Global header information:
name: "next_new_rwf"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Calibration/rwf/

# Block for defining the larsoft setup. Reference a file
software: "/n/holylfs02/LABS/guenette_lab/production/yml-configs/next/new/icnext.yml"

# Block for defining stages.  Can include multiple stages
stages:

    - tl:
        fcl:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/create_rwf_template.conf
        n_jobs: 165
        city: diomira
        max_concurrent_jobs: 200
        events_per_job: -1
        input:
            dataset: NEW_Tl_disk_close_to_anode_7bar_5mev_detsim # Can be none or a name
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Calibration/rwf/Tl
            dataset: NEW_Tl_disk_close_to_anode_7bar_5mev_rwf
            anaonly: false
        memory: 4000
        time: 48:00:00


    - cs:
        fcl:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/create_rwf_template.conf
        n_jobs: 60
        city: diomira
        max_concurrent_jobs: 200
        events_per_job: -1
        input:
            dataset: NEW_Cs_int_port_anode_7bar_0mm_10mev_detsim # Can be none or a name
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Calibration/rwf/Cs
            dataset: NEW_Cs_int_port_anode_7bar_0mm_10mev_rwf
            anaonly: false
        memory: 4000
        time: 48:00:00
