# Global header information:
name: "next_new_pmaps"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Calibration/pmaps/

# Block for defining the larsoft setup. Reference a file
software: "/n/holylfs02/LABS/guenette_lab/production/yml-configs/next/new/icnext.yml"

# Block for defining stages.  Can include multiple stages
stages:

    - tl:
        fcl:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/create_pmaps.conf
        n_jobs: 165
        city: diomira
        max_concurrent_jobs: 165
        events_per_job: -1
        input:
            dataset: NEW_Tl_disk_close_to_anode_7bar_5mev_rwf # Can be none or a name
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Calibration/pmaps/Tl
            dataset: NEW_Tl_disk_close_to_anode_7bar_5mev_pmaps
            anaonly: false
        memory: 4000
        time: 48:00:00


    - cs:
        fcl:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/create_pmaps.conf
        n_jobs: 60
        city: diomira
        max_concurrent_jobs: 60
        events_per_job: -1
        input:
            dataset: NEW_Cs_int_port_anode_7bar_0mm_10mev_rwf # Can be none or a name
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/Calibration/pmaps/Cs
            dataset: NEW_Cs_int_port_anode_7bar_0mm_10mev_pmaps
            anaonly: false
        memory: 4000
        time: 48:00:00
