# Global header information:
name: "mcc8.6_bnb_plus_cosmics"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: &top_dir /n/holylfs/LABS/guenette_lab/data/production/mcc8.6/bnb_plus_cosmics

# Block for defining the larsoft setup.  All fields required
larsoft:
    # REQUIRED: List of product areas.  All must contain 'setup' and all will be called
    product_areas:
        - /n/holylfs/LABS/guenette_lab/software/larsoft
    # OPTIONAL: set up additional local product areas:
    # local_areas:
        # - /home/cadams/sbndcode/localProducts_larsoft_v06_50_00_e14_prof
    # REQUIRED: Specific product to set up (larsoft, uboonecode, sbndcode, etc)
    product: uboonecode
    # REQUIRED: Version of product to set up
    version: v06_26_01_10
    # REQUIRED: Qualifiers to use for this product
    quals: e10:prof

# Block for defining stages.  Can include multiple stages
stages:

    # Genie generation
    - generation:
        # REQUIRED: name of fcl
        fcl:
            - /n/holylfs/LABS/guenette_lab/production/fcl/prodgenie_bnb_nu_cosmic_uboone_harvard.fcl
            - standard_g4_spacecharge_uboone.fcl
            - standard_detsim_uboone.fcl
            - reco_uboone_mcc8_driver_stage1_reduced.fcl
            - reco_uboone_mcc8_driver_stage2_reduced.fcl
        # REQUIRED: number of jobs to run
        n_jobs: 15000
        # OPTIONAL: maximum number of jobs to run simultaneously
        max_concurrent_jobs: 450
        # REQUIRED: number of events per job
        # -1 is "all events in the input file[s]" and is the default
        events_per_job: 50
        # REQUIRED: input definition
        input:
            # REQUIRED: input type
            dataset: none # Can be none or a name

            #OPTIONAL: number of files per job, default == 1
            # n_files: 1
        # REQUIRED: output definition
        output:
            #REQUIRED: output location
            # Must be a location for outputfiles, will add stage name if not there
            location: *top_dir
            # The following lines are not yet implemented
            #REQUIRED: dataset name (will be stored in this projects database)
            dataset: bnb_plus_cosmics_mcc86_reco2
            #REQUIRED: skip root files - default false
            anaonly: false

        # REQUIRED: required memory size - default 4000, units are MB
        memory: 4000
        # REQUIRED: time limit.  Default 6 hours.  Format HH:MM:SS
        time: "12:00:00"

