###################################
#SPACES ONLY
###################################

# Global header information:
name: "mcc8.6_bnb_plus_cosmics"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs/LABS/guenette_lab/production/mcc8.6/bnb_plus_cosmics

# Block for defining the larsoft setup.  All fields required
larsoft:
    # REQUIRED: List of product areas.  All must contain 'setup' and all will be called
    product_areas:
        - /n/holylfs/LABS/guenette_lab/software/larsoft
        # - /data/products/sbnd
    # OPTIONAL: set up additional local product areas:
    # local_areas:
        # - /home/cadams/sbndcode/localProducts_larsoft_v06_50_00_e14_prof
    # REQUIRED: Specific product to set up (larsoft, uboonecode, sbndcode, etc)
    product: uboonecode
    # REQUIRED: Version of product to set up
    version: v06_26_01_10
    # REQUIRED: Qualifiers to use for this product
    quals: e10:prof

# Block for defining stages.  Can include multiple stages
stages:
    # Example generation stage.  Some fields required, others optional
    generation:
        # REQUIRED: name of fcl
        fcl: prodgenie_bnb_nu_cosmic_uboone.fcl
        # REQUIRED: number of jobs to run
        n_jobs: 4
        # REQUIRED: number of events per job
        # -1 is "all events in the input file[s]" and is the default
        events_per_job: 10
        # REQUIRED: input definition
        input:
            # REQUIRED: input type
            type: none # Can be none or a stage
            # REQUIRED: input location
            location: none # can be none if type is none, otherwise must be a path to ... TODO
            #OPTIONAL: number of files per job, default == 1
            # n_files: 1
        # REQUIRED: output definition
        output:
            #REQUIRED: output type
            type: sam # Can be either a sam dataset or none.  List of files is generated automatically
            #REQUIRED: output location
            location: /data/test/generation/ # Must be a location for outputfiles
            #OPTIONAL: skip root files - default false
            anaonly: false
            #OPTIONAL: output file base name.  Default is "%ifb" (input file base)
            basename: none
        # REQUIRED: required memory size - default 4000, units are MB
        memory: 4000
        # REQUIRED: time limit.  Default 6 hours.  Format HH:MM:SS
        time: 06:00:00

        # # OPTIONAL: extra larsoft commands
        # # If used, entire string is added to larsoft command
        # Not yet implemented
        # extra_commands: none