# Global header information:
name: "sbnd_dl_cosmics"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: &top_dir /n/holylfs/LABS/guenette_lab/data/production/sbnd_dl/cosmics_larcv

# Block for defining the software setup.  All fields required
software:
    type: gallery
    # REQUIRED: List of product areas.  All must contain 'setup' and all will be called
    product_areas:
        - /n/holylfs/LABS/guenette_lab/software/larsoft
    # OPTIONAL: set up additional local product areas:
    setup_scripts:
        - /n/holylfs/LABS/guenette_lab/users/cadams/larcv/configure.sh
        - /n/holylfs/LABS/guenette_lab/users/cadams/gallery-framework/config/setup.sh
    # REQUIRED: Specific product to set up (larsoft, uboonecode, sbndcode, etc)
    product: larsoftobj
    # REQUIRED: Version of product to set up
    version: v1_39_00
    # REQUIRED: Qualifiers to use for this product
    quals: e15:prof

# Block for defining stages.  Can include multiple stages
stages:

    # Genie generation
    - larcv:
        # REQUIRED: name of fcl
        fcl:
            - /n/holylfs/LABS/guenette_lab/users/cadams/gallery-framework/UserDev/SuperaLight/supera_sbnd.py
        # REQUIRED: number of jobs to run
        n_jobs: 400
        # OPTIONAL: maximum number of jobs to run simultaneously
        max_concurrent_jobs: 50
        # REQUIRED: number of events per job
        # -1 is "all events in the input file[s]" and is the default
        events_per_job: 50
        # REQUIRED: input definition
        input:
            # REQUIRED: input type
            dataset: none # Can be none or a name

            #OPTIONAL: number of files per job, default == 1
            # n_files: 1
        # REQUIRED: output definition
        output:
            #REQUIRED: output location
            # Must be a location for outputfiles, will add stage name if not there
            location: *top_dir
            # The following lines are not yet implemented
            #REQUIRED: dataset name (will be stored in this projects database)
            dataset: sbnd_dl_cosmics_larsoft
            #REQUIRED: skip root files - default false
            anaonly: false

        # REQUIRED: required memory size - default 4000, units are MB
        memory: 4000
        # REQUIRED: time limit.  Default 6 hours.  Format HH:MM:SS
        time: 06:00:00

