# Global header information:
name: "numu_ccinc"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: &top_dir /n/holylfs02/LABS/guenette_lab/data/users/cadams/numu_ccinc

# Block for defining the larsoft setup.  All fields required
software:
    type: larsoft
    # REQUIRED: List of product areas.  All must contain 'setup' and all will be called
    product_areas:
        - /n/holylfs02/LABS/guenette_lab/software/larsoft
    # local_areas:
        # - /n/holylfs02/LABS/guenette_lab/users/cadams/marco/larsoft_dev/localProducts_larsoft_v06_26_01_09_e10_prof/
    # REQUIRED: Specific product to set up (larsoft, uboonecode, sbndcode, etc)
    product: uboonecode
    # REQUIRED: Version of product to set up
    version: v06_26_01_13
    # REQUIRED: Qualifiers to use for this product
    quals: e10:prof

# Block for defining stages.  Can include multiple stages
stages:

    # Genie generation
    - xsec_ana:
        # REQUIRED: name of fcl
        fcl:
            - run_ubxsec_mc_bnbcosmic.fcl
        # REQUIRED: number of jobs to run
        n_jobs: 198
        # OPTIONAL, used to calculate number of makeup jobs
        event_target: 49300
        # OPTIONAL: maximum number of jobs to run simultaneously
        # max_concurrent_jobs: 50
        # REQUIRED: number of events per job
        # -1 is "all events in the input file[s]" and is the default
        events_per_job: -1
        # REQUIRED: input definition
        input:
            # REQUIRED: input type
            dataset: bnb_plus_cosmics_mcc86_reco2_dev_high_mem # Can be none or a name

            #OPTIONAL: number of files per job, default == 1
            n_files: 5
        # REQUIRED: output definition
        output:
            #REQUIRED: output location
            # Must be a location for outputfiles, will add stage name if not there
            location: *top_dir
            # The following lines are not yet implemented
            #REQUIRED: dataset name (will be stored in this projects database)
            dataset: marco_ubxsec_ana_dev_high_mem
            #REQUIRED: skip root files - default false
            anaonly: true
            ana_name: "ubxsec_output_mc_bnbcosmic"

        # REQUIRED: required memory size - default 4000, units are MB
        memory: 4000
        # REQUIRED: time limit.  Default 6 hours.  Format HH:MM:SS
        time: 06:00:00

