# Global header information:
name: "next_new_detsim"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_04_00/art/

# Block for defining the larsoft setup. Reference a file
software: "/n/holylfs02/LABS/guenette_lab/production/yml-configs/next/new_bkg_sim/artnext.yml"

# Block for defining stages.  Can include multiple stages
stages:
    - single:
        config:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/DepletedXe_detsim.fcl
        n_jobs: 400
        events_per_job: -1
        input:
            dataset: NEW_SINGLE_E_10bar_nexus # Can be none or a name
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_03_01/art/single/
            dataset: NEW_SINGLE_E_10bar_detsim
            anaonly: false
            subproject: detsim
        memory: 4000
        time: 48:00:00

    - double:
        config:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/DepletedXe_detsim.fcl
        n_jobs: 400
        events_per_job: -1
        input:
            dataset: NEW_DOUBLE_E_10bar_nexus # Can be none or a name
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_03_01/art/double/
            dataset: NEW_DOUBLE_E_10bar_detsim
            anaonly: false
            subproject: detsim
        memory: 4000
        time: 48:00:00
