# Global header information:
name: "next_new_pmaps_dl"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_04_00/pmaps/

# Block for defining the larsoft setup. Reference a file
software: "/n/holylfs02/LABS/guenette_lab/production/yml-configs/next/new_dl_sample/icnext.yml"

# Block for defining stages.  Can include multiple stages
stages:

    - single:
        config:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/createPMAP_lowbackground.conf
        n_jobs: 400
        events_per_job: -1
        city: irene
        input:
            dataset: NEW_SINGLE_E_10bar_rwf
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_04_00/pmaps/single/
            dataset: NEW_SINGLE_E_10bar_pmaps
            anaonly: false
            subproject: pmaps
        memory: 4000
        time: 48:00:00

    - double:
        config:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/createPMAP_lowbackground.conf
        n_jobs: 400
        events_per_job: -1
        city: irene
        input:
            dataset: NEW_DOUBLE_E_10bar_rwf
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_04_00/pmaps/double/
            dataset: NEW_DOUBLE_E_10bar_pmaps
            anaonly: false
            subproject: pmaps
        memory: 4000
        time: 48:00:00
