# Global header information:
name: "next_new_rwf_dl"
# REQUIRED: top project dirctory, work files go here, output files can be elsewhere
top_dir: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_04_00/rwf/

# Block for defining the larsoft setup. Reference a file
software: "/n/holylfs02/LABS/guenette_lab/production/yml-configs/next/new_radon/icnext.yml"

# Block for defining stages.  Can include multiple stages
stages:

    - single:
        config:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/createRWF_lowbackgroundrun.conf
        n_jobs: 4
        events_per_job: -1
        city: diomira
        input:
            dataset: NEW_SINGLE_E_10bar_detsim
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_04_00/rwf/single/
            dataset: NEW_SINGLE_E_10bar_rwf
            anaonly: false
            subproject: rwf
        memory: 4000
        time: 48:00:00

    - double:
        config:
            - /n/holylfs02/LABS/guenette_lab/production/fcl/next/createRWF_lowbackgroundrun.conf
        n_jobs: 400
        events_per_job: -1
        city: diomira
        input:
            dataset: NEW_DOUBLE_E_10bar_detsim
            # n_files: 1
        output:
            location: /n/holylfs02/LABS/guenette_lab/data/NEXT/NEXTNEW/MC/DL_SAMPLE/NEXUS_NEXT_v1_04_00/rwf/double/
            dataset: NEW_DOUBLE_E_10bar_rwf
            anaonly: false
            subproject: rwf
        memory: 4000
        time: 48:00:00
